version: '3.9'

services:

  nginx:
    build:
      context: ../..
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ../:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8002:80
    networks:
      - backend


  php-fpm:
    build:
      context: ../..
      dockerfile: php-fpm/Dockerfile
    restart: unless-stopped
    container_name: php
    volumes:
      - ../:/application
      - ./php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    networks:
      - backend
  db:
      image: 'bitnami/postgresql:latest'
      restart: always
      environment:
          POSTGRESQL_USERNAME: admin
          POSTGRESQL_PASSWORD: root123
          POSTGRESQL_DATABASE: my_database
      ports:
          - 5432:5432

      networks:
       - backend



networks:
  backend:
    name: My_network
    driver: bridge


