version: '3.9'

services:
    mysql:
        image: bitnami/mariadb:latest
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root123
            MYSQL_DATABASE: laravel2
        ports:
            - 3306:3306
