FROM bitnami/php-fpm:8.0

WORKDIR /application

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y imagemagick libzip-dev libpng-dev nano

# Install selected extensions and other stuff

#RUN #docker-php-ext-install pdo pdo_mysql
#    && docker-php-ext-enable pdo_mysql
RUN apt-get update
#RUN #apt-get -y install php8.0-pgsql php8.0-mysql php8.0-sqlite php8.0-redis php8.0-bcmath php8.0-gd php8.0-imagick php8.0-dev
#RUN #docker-php-ext-install pdo_pgsql pgsql

COPY ./docker/php-fpm/php-ini-overrides.ini /etc/php/8.0/fpm/conf.d/99-overrides.ini
COPY ./ /application

RUN rm -rf /application/docker && chmod -R 777 /application/bootstrap && chmod -R 777 /application/storage
